### ISSUE TITLE
Per controller leader election?

### ISSUE THREAD

**Issue by GrigoriyMikhalkin** [timebertt/kubernetes-controller-sharding#1]
Hey Tim!

I guess you can implement this by disabling leader election on manager) But my guess, you want to enable it only for selected controllers. Am i right or totally misunderstood the problem)?

Anyway, few years ago there was a discussion in controller-runtime [on per-controller leader election](https://github.com/kubernetes-sigs/controller-runtime/issues/364) and even [implementation(closed) of this](https://github.com/kubernetes-sigs/controller-runtime/pull/444).

**Comment by timebertt** [comment]
Hi @GrigoriyMikhalkin!

Thanks for your hint and the reference.
Though, my idea here goes even further than distributing controllers across multiple manager instances (per controller leader election). My goal is rather to distribute reconciliations as such across multiple controller instances (sharding).

I explained the background and motivation a bit in https://github.com/timebertt/kubernetes-controller-sharding/pull/7.
Feel free to take a look and come back with questions and ideas! :)
